collections:
  - name: "products"
    label: "Inventory"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Collection", name: "category", widget: "select", options: ["KINETIC", "THE EXCHANGE", "URBAN ARCHIVE", "HERITAGE"]}
      - {label: "Price (NGN)", name: "price", widget: "number"}
      - {label: "Main Image URL", name: "image", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
